ALTER TABLE deals
  ADD COLUMN IF NOT EXISTS pickup_address TEXT NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS pickup_date TIMESTAMPTZ,
  ADD COLUMN IF NOT EXISTS delivery_address TEXT NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS delivery_date TIMESTAMPTZ,
  ADD COLUMN IF NOT EXISTS courier TEXT NOT NULL DEFAULT '';
